### ISSUE TITLE
Automatic replacement of AppId/package with Github Actions

### ISSUE THREAD

**Issue by martinbonnin** [cortinico/kotlin-android-template#18]
I just bumped into the Jetbrains template for IntelliJ plugins (https://github.com/JetBrains/intellij-platform-plugin-template#getting-started). They have a Github Action that replaces the template values with values from the fork repo. I think it'd be a great addition to this template: it'll make sure users don't forget to remove the default value and save some manual configuration.

I'm not sure I'll have a lot of time to work on this but if someone feels like investigating Github Actions, I think that'd be a good fit.

**Comment by cortinico** [comment]
> They have a Github Action that replaces the template values with values from the fork repo. I think it'd be a great addition to this template: it'll make sure users don't forget to remove the default value and save some manual configuration.

Agree 👍 I was actually looking into using https://github.com/cookiecutter/cookiecutter for a similar solution. The problem is that this would leave the template in an unbuildable state. 

Using the GH Actions workflow seems like a great alternative that would still keep the template buildable (though looks a bit hacky 😅). I wish Github could provide some sort of minimal customisation for the GH Templates
